services:
  backend:
    build: .
    container_name: kanban-backend
    ports:
      - "8085:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
    environment:
      SPRING_POSTGRES_URL: jdbc:postgresql://localhost:5434/kanban_db
      SPRING_POSTGRES_PASSWORD: secret123
      SPRING_POSTGRES_USER: postgres
#    networks:
#      - kanban-net

networks:
  kanban-net:
    external: true